server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/humanresource
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


  security:
    user:
      name: ADMINISTRATOR
      password: ADMINISTRATOR

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: serkan.klcdr@gmail.com
    password: xlclftccllcqlnav
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ✅ JWT Secret Key Eklendi
my-jwt:
  secret-key: mySuperSecretKey1234567890

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  file:
    name: humanresource.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
  level:
    root: info
