server:
  port: 9090


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${HUMANRESOURCE_DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    jpa:
      hibernate:
        ddl-auto: create-drop
    security:
      user:
        name: ADMINISTRATOR
        password: ADMINISTRATOR



springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  file:
    name: humanresource.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
  level:
    root: info


