server:
  port: 9090


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/humanresource
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    username: elifcangoktepe@gmail.com
    password: humanresource**



springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  file:
    name: humanresource.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
  level:
    root: info


